### ISSUE TITLE
BUG: Not saving learned model throws exception

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#107]
iBioSim Version 2.8.4

Operating system: Linux

Bug reported by: l.watanabe@utah.edu

Description:
When I tried to learn a model, if you cancel the save option for the resulting model, an exception is thrown

Stack trace:
java.lang.NullPointerException
	at learn.GCM.LearnGCM.saveModel(LearnGCM.java:1223)
	at learn.GCM.LearnGCM.runGeneNet(LearnGCM.java:1776)
	at learn.GCM.LearnGCM.run(LearnGCM.java:1437)
	at java.lang.Thread.run(Thread.java:745)

**Comment by leandrohw** [comment]
This seems to be fixed. The exception is gone when you don't save a model after learn.
