### ISSUE TITLE
BUG: index out of bound exception on the generation of PRISM CTMC file

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#113]
When converting the majority SBML model (see stochastic_model_checking
package sent separately) to prism file, it generated the following
exception:

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.sbml.jsbml.ASTNode.getChild(ASTNode.java:2311)
    at
biomodel.util.SBMLutilities.convertMath2PrismProperty(SBMLutilities.java:2454)
    at biomodel.parser.BioModel.convertLPN2PRISM(BioModel.java:837)
    at analysis.main.Run.execute(Run.java:827)
    at analysis.main.AnalysisView.run(AnalysisView.java:1124)
    at analysis.main.AnalysisThread.run(AnalysisThread.java:24).

**Comment by buggsley** [comment]
The same applies to repressilator and speedInd.
