### ISSUE TITLE
BUG: Unable to add properties to property file

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#116]
This bug occurred when converting dual_feedback_oscillator.xml to a PRISM
model (see stack trace below). It started to happen after JParts dependency
got removed.

java.lang.IllegalArgumentException: Invalid SId:
St((((AraC>=60)&&(PF((t<=1000),(AraC<60))>=0.95))||((AraC<60)&&(PF((t<=1000),(AraC>=60))>=0.95))))_dg
    at org.jlibsedml.SId.<init>(SId.java:9)
    at
org.jlibsedml.AbstractIdentifiableElement.<init>(AbstractIdentifiableElement.java:69)
    at org.jlibsedml.DataGenerator.<init>(DataGenerator.java:47)
    at org.jlibsedml.SedML.addSimpleSpeciesAsOutput(SedML.java:628)
    at graph.Graph.saveSEDML(Graph.java:5572)
    at analysis.main.AnalysisView.saveSEDML(AnalysisView.java:1576)
    at analysis.main.AnalysisView.save(AnalysisView.java:1517)
    at analysis.main.AnalysisView.run(AnalysisView.java:1004)
    at analysis.main.AnalysisThread.run(AnalysisThread.java:24)

**Comment by cjmyers** [comment]
Cannot find the line of code causing this problem.  Moving to 3.1.
