### ISSUE TITLE
BUG: Exceptions on saving a model with parameter sweep

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#137]
iBioSim Version 2.8.6

Operating system: Mac OS X

Bug reported by: zhen.zhang@utah.edu

Description:
I was following the online System Biology Tutorial (version 2.8) tutorial to do parameter sweep for the degradation rate for CII. After viewing the TSD graph simulation results, I tried to save it, and got these exceptions.

Stack trace:
java.lang.IllegalArgumentException: Invalid SId: CI_total_lamda__kd_0.0075_Sweep=0.005_1_var
	at org.jlibsedml.SId.<init>(SId.java:9)
	at org.jlibsedml.AbstractIdentifiableElement.<init>(AbstractIdentifiableElement.java:69)
	at org.jlibsedml.Variable.<init>(Variable.java:46)
	at analysis.main.SEDMLutilities.getDataGenerator(SEDMLutilities.java:95)
	at graph.Graph.saveSEDML(Graph.java:5600)
	at graph.Graph.save(Graph.java:5675)
	at main.Gui.actionPerformed(Gui.java:3111)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
[SysBioTutorial.zip](https://github.com/MyersResearchGroup/iBioSim/files/721899/SysBioTutorial.zip)

**Comment by cjmyers** [comment]
I believe this one is fixed.  Zhen: do you mind having a look?

**Comment by zgzn** [comment]
Works now.
