### ISSUE TITLE
FEATURE: add support for general biochemical reactions in logical abstraction

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#175]
By using reaction splitization idea, support arbitrary reactions when mapping to a logical model.

**Comment by buggsley** [comment]
I got the following exception when I tried this (will send example in separate
message).

Exception in thread "Thread-9" java.lang.NullPointerException
	at biomodel.parser.BioModel.replaceParams(BioModel.java:966)
	at biomodel.parser.BioModel.convertToLHPN(BioModel.java:861)
	at analysis.Run.execute(Run.java:687)
	at analysis.AnalysisView.run(AnalysisView.java:2207)
	at analysis.AnalysisThread.run(AnalysisThread.java:24)
