### ISSUE TITLE
BUG: unhandled null pointer

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#201]
iBioSim Version 2.8.4

Operating system: Mac OS X

Bug reported by: tramy.nguy@gmail.com

Description:
Model generator isn't handling when ComponentDefinition is missing. Give proper error message when this happens.

Stack trace:
java.lang.NullPointerException
	at sbol.assembly.ModelGenerator.isComplexDefinition(ModelGenerator.java:628)
	at sbol.assembly.ModelGenerator.isSpeciesDefinition(ModelGenerator.java:615)
	at sbol.assembly.ModelGenerator.isSpeciesComponent(ModelGenerator.java:611)
	at sbol.assembly.ModelGenerator.generateModel(ModelGenerator.java:69)
	at main.Gui.generateSBMLFromSBOL(Gui.java:6678)
	at main.Gui.actionPerformed(Gui.java:2142)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by buggsley** [comment]
Is this still happening?  How to reproduce.

> iBioSim Version 2.8.4
> 
> Operating system: Mac OS X
> 
> Bug reported by: tramy.nguy@gmail.com
> 
> Description:
> Model generator isn't handling when ComponentDefinition is missing. Give
proper
> error message when this happens.
> 
> Stack trace:
> java.lang.NullPointerException
> 	at sbol.assembly.ModelGenerator.isComplexDefinition(ModelGenerator.java:628)
> 	at sbol.assembly.ModelGenerator.isSpeciesDefinition(ModelGenerator.java:615)
> 	at sbol.assembly.ModelGenerator.isSpeciesComponent(ModelGenerator.java:611)
> 	at sbol.assembly.ModelGenerator.generateModel(ModelGenerator.java:69)
> 	at main.Gui.generateSBMLFromSBOL(Gui.java:6678)
> 	at main.Gui.actionPerformed(Gui.java:2142)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
> 	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.Component.processMouseEvent(Component.java:6505)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
> 	at java.awt.Component.processEvent(Component.java:6270)
> 	at java.awt.Container.processEvent(Container.java:2229)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4861)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2287)
> 	at java.awt.Component.dispatchEvent(Component.java:4687)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2273)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2719)
> 	at java.awt.Component.dispatchEvent(Component.java:4687)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
> 	at java.awt.EventQueue.access$200(EventQueue.java:103)
> 	at java.awt.EventQueue$3.run(EventQueue.java:694)
> 	at java.awt.EventQueue$3.run(EventQueue.java:692)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.awt.EventQueue$4.run(EventQueue.java:708)
> 	at java.awt.EventQueue$4.run(EventQueue.java:706)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
> 
>

**Comment by tramyn** [comment]
This issue is resolved because if you import an SBOL 2.0 file that will call the SBOL2SBML converter, iBioSim will display an SBOL error that indicates to the user that their SBOL file to be loaded into iBioSim workspace contains invalid SBOL data. This means that if the user has an SBOL file that has a functionalComponent that refers to an undeclared ComponentDefinition within the file, the user will not be able to add their SBOL data model into the iBioSim project workspace.
