### ISSUE TITLE
BUG: null pointer exception on opening an SBML file

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#217]
When trying to open toggle_switch.xml (see stochastic_model_checking
package sent separately), the following null pointer exception occurred.
Also, there was an error pop-up window saying" You must select a valid SBML
file". Does this mean this file is invalid?

java.lang.NullPointerException
    at
biomodel.gui.schematic.BioGraph.addSpeciesReferenceGlyph(BioGraph.java:213)
    at biomodel.gui.schematic.BioGraph.buildGraph(BioGraph.java:726)
    at biomodel.gui.schematic.Schematic.display(Schematic.java:219)
    at biomodel.gui.schematic.Schematic.<init>(Schematic.java:200)
    at biomodel.gui.schematic.ModelEditor.buildGui(ModelEditor.java:1855)
    at biomodel.gui.schematic.ModelEditor.<init>(ModelEditor.java:244)
    at main.Gui.openSBML(Gui.java:6954)
    at main.Gui.executeMouseClickEvent(Gui.java:8972)
    at main.Gui.mouseClicked(Gui.java:10084)
    at
java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6538)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by buggsley** [comment]
I think this is fixed.

Chris

**Comment by leandrohw** [comment]
I don't have access to this model. However, I haven't had any problems opening up other models.

**Comment by cjmyers** [comment]
closing
