### ISSUE TITLE
BUG: Saving previous analysis view generated null pointer exception

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#226]
Opening an existing BioSim project generated the warnings below.
12:03:00 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
Unexpected [Element: <annotation [Namespace:
http://sed-ml.org/sed-ml/level1/version2]/>]
Warning: Could not get charToByteConverterClass!

Opening previous analysis view, and then saving it (even without any
changes to it), generated the an error window "Unable to save
parameter file", with exceptions shown below. Note that clicking OK on
the error window triggers the same exception again.

java.lang.NullPointerException
    at biomodel.gui.schematic.ModelEditor.saveParams(ModelEditor.java:844)
    at biomodel.gui.movie.MovieContainer.savePreferences(MovieContainer.java:833)
    at main.Gui.actionPerformed(Gui.java:3140)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
    at biomodel.gui.schematic.ModelEditor.saveParams(ModelEditor.java:844)
    at main.Gui.actionPerformed(Gui.java:3132)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by buggsley** [comment]
It appears that saving of parameters is happening before the analysis view
creates the task in SED-ML.  I've added a 
check for the null pointer.  This should be working for now, but I need to see
why the saves are happening out-of-
order.  Please test, but you should not close as this is a hack.

> Opening an existing BioSim project generated the warnings below.
> 12:03:00 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
> Unexpected [Element: <annotation [Namespace:
> http://sed-ml.org/sed-ml/level1/version2]/>]
> Warning: Could not get charToByteConverterClass!
> 
> Opening previous analysis view, and then saving it (even without any
> changes to it), generated the an error window "Unable to save
> parameter file", with exceptions shown below. Note that clicking OK on
> the error window triggers the same exception again.
> 
> java.lang.NullPointerException
>     at biomodel.gui.schematic.ModelEditor.saveParams(ModelEditor.java:844)
>     at biomodel.gui.movie.MovieContainer.savePreferences(MovieContainer.java:833)
>     at main.Gui.actionPerformed(Gui.java:3140)
>     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
>     at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
>     at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>     at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>     at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
>     at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
>     at java.awt.Component.processMouseEvent(Component.java:6535)
>     at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>     at java.awt.Component.processEvent(Component.java:6300)
>     at java.awt.Container.processEvent(Container.java:2236)
>     at java.awt.Component.dispatchEventImpl(Component.java:4891)
>     at java.awt.Container.dispatchEventImpl(Container.java:2294)
>     at java.awt.Component.dispatchEvent(Component.java:4713)
>     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
>     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
>     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
>     at java.awt.Container.dispatchEventImpl(Container.java:2280)
>     at java.awt.Window.dispatchEventImpl(Window.java:2750)
>     at java.awt.Component.dispatchEvent(Component.java:4713)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
>     at java.awt.EventQueue.access$500(EventQueue.java:97)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.awt.EventQueue$3.run(EventQueue.java:703)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
>     at java.awt.EventQueue$4.run(EventQueue.java:731)
>     at java.awt.EventQueue$4.run(EventQueue.java:729)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> java.lang.NullPointerException
>     at biomodel.gui.schematic.ModelEditor.saveParams(ModelEditor.java:844)
>     at main.Gui.actionPerformed(Gui.java:3132)
>     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
>     at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
>     at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>     at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>     at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
>     at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
>     at java.awt.Component.processMouseEvent(Component.java:6535)
>     at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>     at java.awt.Component.processEvent(Component.java:6300)
>     at java.awt.Container.processEvent(Container.java:2236)
>     at java.awt.Component.dispatchEventImpl(Component.java:4891)
>     at java.awt.Container.dispatchEventImpl(Container.java:2294)
>     at java.awt.Component.dispatchEvent(Component.java:4713)
>     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
>     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
>     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
>     at java.awt.Container.dispatchEventImpl(Container.java:2280)
>     at java.awt.Window.dispatchEventImpl(Window.java:2750)
>     at java.awt.Component.dispatchEvent(Component.java:4713)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
>     at java.awt.EventQueue.access$500(EventQueue.java:97)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.awt.EventQueue$3.run(EventQueue.java:703)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
>     at java.awt.EventQueue$4.run(EventQueue.java:731)
>     at java.awt.EventQueue$4.run(EventQueue.java:729)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
>

**Comment by buggsley** [comment]
The exceptions disappeared. However, I am not sure if this was due to your code
fix. I downloaded the iBioSim 2.9 zip file, but could not reproduce these
exceptions.

**Comment by buggsley** [comment]
Not sure how to reproduce.

Chris

**Comment by leandrohw** [comment]
Following the provided steps did not cause any problem. Closing this one.
