### ISSUE TITLE
BUG: Browser option in Analysis view not working

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#231]
iBioSim Version 2.9.1

Operating system: Linux

Bug reported by: dtrang.tran@utah.edu

Description:
An unhandled exception popping out saying java.lang.IllegalArgumentException: Invalid SId: neg-ssa_sim

Stack trace:
java.lang.IllegalArgumentException: Invalid SId: neg-ssa_sim
at org.jlibsedml.SId.<init>(SId.java:9)
at org.jlibsedml.AbstractIdentifiableElement.<init>(AbstractIdentifiableElement.java:69)
at org.jlibsedml.Simulation.<init>(Simulation.java:29)
at org.jlibsedml.SteadyState.<init>(SteadyState.java:6)
at analysis.main.AnalysisView.saveSEDML(AnalysisView.java:1698)
at analysis.main.AnalysisView.executeRun(AnalysisView.java:3049)
at main.Gui.actionPerformed(Gui.java:3439)

**Comment by leandrohw** [comment]
Looks like this happened because there was a '-' character in the id of some object. I can't reproduce this because iBioSim does not allow invalid characters on the creation of new objects.
