### ISSUE TITLE
nullpointer exception when trying to use learn method

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#270]
iBioSim Version 2.9.5

Operating system: Windows 8.1

Bug reported by: kyledecurtis@mail.usf.edu

Description:
nullpointer exception when trying to use learn method. Imported data set levels and clicked save and run

Stack trace:
java.lang.NullPointerException
	at backend.learn.genenet.SpeciesCollection.getColumn(SpeciesCollection.java:35)
	at backend.learn.genenet.Learn.getDiscreteLevels(Learn.java:176)
	at backend.learn.genenet.Learn.EncodeExpts(Learn.java:151)
	at backend.learn.genenet.Learn.learnNetwork(Learn.java:131)
	at backend.learn.genenet.Run.run(Run.java:32)
	at frontend.learn.GCM.LearnGCM.run(LearnGCM.java:1443)
	at java.lang.Thread.run(Unknown Source)

**Comment by leandrohw** [comment]
This is related to another issue where ids in the model and experimental data do not match. Granted, the learn could processed assuming the species not matched has constant value of 0 but this is not meaningful. Rather, I added a error display message to notify the user about the problem. Closing this one.
