### ISSUE TITLE
When running a learn view a nullpointrerexception is thrown

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#278]
iBioSim Version 2.9.5

Operating system: Windows 10

Bug reported by: brmckalip@gmail.com

Description:
ibiosim v2.9.5 on windows 10

this doesn't happen on every project, I'm able to successfully run the learn view with graphviz installed on another set of species in another project, so I'm not sure how to reproduce this bug. using 4 bins each for 3 species with the following (suggested) levels
levels:
CI: 4, 13, 31
LaCI: 0, 0, 9990
TetR: 2, 8, 20

Error message given:
java.lang.NullPointerException
	at backend.learn.genenet.SpeciesCollection.getColumn(SpeciesCollection.java:35)
	at backend.learn.genenet.Learn.getDiscreteLevels(Learn.java:176)
	at backend.learn.genenet.Learn.EncodeExpts(Learn.java:151)
	at backend.learn.genenet.Learn.learnNetwork(Learn.java:131)
	at backend.learn.genenet.Run.run(Run.java:32)
	at frontend.learn.GCM.LearnGCM.run(LearnGCM.java:1443)
	at java.lang.Thread.run(Unknown Source)

Stack trace:
java.lang.NullPointerException
	at backend.learn.genenet.SpeciesCollection.getColumn(SpeciesCollection.java:35)
	at backend.learn.genenet.Learn.getDiscreteLevels(Learn.java:176)
	at backend.learn.genenet.Learn.EncodeExpts(Learn.java:151)
	at backend.learn.genenet.Learn.learnNetwork(Learn.java:131)
	at backend.learn.genenet.Run.run(Run.java:32)
	at frontend.learn.GCM.LearnGCM.run(LearnGCM.java:1443)
	at java.lang.Thread.run(Unknown Source)

**Comment by zgzn** [comment]
Here is the project causing this issue. 
[HW3-problem2.zip](https://github.com/MyersResearchGroup/iBioSim/files/880315/HW3-problem2.zip)

**Comment by leandrohw** [comment]
This is happening because the id of the species in the experimental data and the species in the model are different. Ids are case-sensitive. Added an error message to notify the user that the species in the model and the data are not matching. Closing this one.
