### ISSUE TITLE
BUG: Move Random error rkf45 (java)

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#29]
Bug reported by: jeffrey.theisen@utah.edu

Description:
When I simulate a cell with random movement in the rkf45 (java) simulator it comes up with a NullPointerException.  This error does not come up when using the SSA-Direct (java) simulator.

Stack trace:
java.lang.NullPointerException
	at analysis.dynamicsim.Simulator.fireEvents(Simulator.java:2183)
	at analysis.dynamicsim.SimulatorODERK.simulate(SimulatorODERK.java:285)
	at analysis.dynamicsim.DynamicSimulation.simulate(DynamicSimulation.java:85)
	at analysis.Run.execute(Run.java:1266)
	at analysis.AnalysisView.run(AnalysisView.java:2214)
	at analysis.AnalysisThread.run(AnalysisThread.java:24)

**Comment by buggsley** [comment]
Well, turns out the information that needed to be setup to support movement in
grids was not setup in the java 
ODE simulator.  It is now, and it should work in the next release.

Chris

> Bug reported by: jeffrey.theisen@utah.edu
> 
> Description:
> When I simulate a cell with random movement in the rkf45 (java) simulator it
> comes up with a NullPointerException.  This error does not come up when using
> the SSA-Direct (java) simulator.
> 
> Stack trace:
> java.lang.NullPointerException
> 	at analysis.dynamicsim.Simulator.fireEvents(Simulator.java:2183)
> 	at analysis.dynamicsim.SimulatorODERK.simulate(SimulatorODERK.java:285)
> 	at analysis.dynamicsim.DynamicSimulation.simulate(DynamicSimulation.java:85)
> 	at analysis.Run.execute(Run.java:1266)
> 	at analysis.AnalysisView.run(AnalysisView.java:2214)
> 	at analysis.AnalysisThread.run(AnalysisThread.java:24)
> 
>

**Comment by buggsley** [comment]
I actually do not get this error anymore, but the move random in rkf45(java)
still does not work as expected.  I have been able to get cells to move randomly
at a regular interval with SSA-Direct(java), but when I run same model with
rkf45(java) the cell moves downwards twice and then stops.  I don't think I have
actually reported this new problem yet, if you would like me to submit that as a
bug let me know.

Jeff
