### ISSUE TITLE
Bug with learn view

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#314]
iBioSim Version 2.9.5

Operating system: Linux

Bug reported by: moschino21@gmail.com

Description:

Stack trace:
java.lang.NullPointerException
	at backend.learn.genenet.SpeciesCollection.getColumn(SpeciesCollection.java:35)
	at backend.learn.genenet.Learn.getDiscreteLevels(Learn.java:176)
	at backend.learn.genenet.Learn.EncodeExpts(Learn.java:151)
	at backend.learn.genenet.Learn.learnNetwork(Learn.java:131)
	at backend.learn.genenet.Run.run(Run.java:32)
	at frontend.learn.GCM.LearnGCM.run(LearnGCM.java:1443)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cjmyers** [comment]
duplicate
