### ISSUE TITLE
simulator: SSA-CR (Dynamic)

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#316]
iBioSim Version 2.9.5

Operating system: Mac OS X

Bug reported by: moschino21@gmail.com

Description:

Stack trace:
java.lang.NullPointerException
	at backend.analysis.dynamicsim.flattened.Simulator.fireEvents(Simulator.java:2398)
	at backend.analysis.dynamicsim.flattened.SimulatorSSACR.simulate(SimulatorSSACR.java:225)
	at backend.analysis.dynamicsim.DynamicSimulation.simulate(DynamicSimulation.java:138)
	at frontend.analysis.Run.execute(Run.java:1260)
	at frontend.analysis.AnalysisView.run(AnalysisView.java:1119)
	at frontend.analysis.AnalysisThread.run(AnalysisThread.java:24)

**Comment by zgzn** [comment]
Tried on lambda in the attached project. 
[SysBioTutorial.zip](https://github.com/MyersResearchGroup/iBioSim/files/914609/SysBioTutorial.zip)

**Comment by cjmyers** [comment]
duplicate
