### ISSUE TITLE
SBML Technology broken during run 

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#338]
A NullPointerException is caught when running SBML Technology 
Exception. 

This error is throwing in Synthesizer.java for portMapIOSpecies(). When getting CompSBasePlugin for a given species, the species that is passed into this method is null. 

iBioSim project for this error is attached below.

Here is the error:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.getCompSBasePlugin(SBMLutilities.java:4725)
	at edu.utah.ece.async.ibiosim.synthesis.SBMLTechMapping.Synthesizer.portMapIOSpecies(Synthesizer.java:377)
	at edu.utah.ece.async.ibiosim.synthesis.SBMLTechMapping.Synthesizer.composeOutput(Synthesizer.java:291)
	at edu.utah.ece.async.ibiosim.synthesis.SBMLTechMapping.Synthesizer.composeSolutionModel(Synthesizer.java:254)
	at edu.utah.ece.async.ibiosim.gui.synthesisView.SynthesisView.importSolutions(SynthesisView.java:460)
	at edu.utah.ece.async.ibiosim.gui.synthesisView.SynthesisView.run(SynthesisView.java:416)
	at edu.utah.ece.async.ibiosim.gui.Gui.synthesizeSBOL(Gui.java:8138)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2855)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[sb400135t_si_001.zip](https://github.com/MyersResearchGroup/iBioSim/files/950168/sb400135t_si_001.zip)

**Comment by tramyn** [comment]
Update:
When getting output species of the solution from SBML technology mapping, a null exception is thrown because the output species of the tech map solution can't find the compartment glyph from the SBML model layout with this id:  Glyph__Cell

**Comment by cjmyers** [comment]
Can you give more detailed steps of how you ran into this error?

**Comment by cjmyers** [comment]
Should be fixed.  Please describe how to test.
