### ISSUE TITLE
Tryiing to  drop a module of a model I made in a project into another model, which is also in the same project.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#348]
iBioSim Version 2.9.5

Operating system: Windows 10

Bug reported by: walterh@mail.usf.edu

Description:

Stack trace:
java.lang.IllegalArgumentException: org.sbml.jsbml.IdentifierException: Cannot set duplicate meta identifier delete_Degradation_Repressor for deletion.
	at org.sbml.jsbml.AbstractSBase.setId(AbstractSBase.java:3094)
	at dataModels.biomodel.util.SBMLutilities.addDeletion(SBMLutilities.java:7033)
	at dataModels.biomodel.util.SBMLutilities.addImplicitDeletions(SBMLutilities.java:7057)
	at dataModels.biomodel.util.SBMLutilities.addImplicitReplacementsDeletions(SBMLutilities.java:7239)
	at dataModels.biomodel.parser.BioModel.updatePorts(BioModel.java:6221)
	at dataModels.biomodel.parser.BioModel.save(BioModel.java:2544)
	at frontend.biomodel.gui.schematic.ModelEditor.save(ModelEditor.java:416)
	at frontend.main.Gui.actionPerformed(Gui.java:3086)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.sbml.jsbml.IdentifierException: Cannot set duplicate meta identifier delete_Degradation_Repressor for deletion.
	at org.sbml.jsbml.AbstractSBase.setId(AbstractSBase.java:3092)
	... 44 more

**Comment by cjmyers** [comment]
Need better checking on meta ids not be duplicate.

**Comment by cjmyers** [comment]
Not sure how to reproduce.  Seems should be setting id not metaId, maybe jsbml bug.
