### ISSUE TITLE
Errors in SSA-CR (Dynamic)

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#352]
iBioSim Version 2.9.5

Operating system: Mac OS X

Bug reported by: moschino21@gmail.com

Description:
Occurred on EColi_fix.xml (will provide separately).

Stack trace:
java.lang.IllegalStateException: No free or removed slots available. Key set full?!!
	at gnu.trove.impl.hash.TIntHash.insertKeyRehash(TIntHash.java:326)
	at gnu.trove.impl.hash.TIntHash.insertKey(TIntHash.java:275)
	at gnu.trove.set.hash.TIntHashSet.add(TIntHashSet.java:194)
	at backend.analysis.dynamicsim.flattened.SimulatorSSACR.updateGroups(SimulatorSSACR.java:1066)
	at backend.analysis.dynamicsim.flattened.SimulatorSSACR.simulate(SimulatorSSACR.java:317)
	at backend.analysis.dynamicsim.DynamicSimulation.simulate(DynamicSimulation.java:138)
	at frontend.analysis.Run.execute(Run.java:1260)
	at frontend.analysis.AnalysisView.run(AnalysisView.java:1119)
	at frontend.analysis.AnalysisThread.run(AnalysisThread.java:24)

**Comment by zgzn** [comment]
Project file is attached. 

[FinalProj.zip](https://github.com/MyersResearchGroup/iBioSim/files/991632/FinalProj.zip)
