### ISSUE TITLE
Duplicate Species Ids

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#384]
iBioSim Version 2.9.6

Operating system: Mac OS X

Bug reported by: myers@ece.utah.edu

Description:
If you annotate two species and/or promoters with the same component, you can get duplicate ids.  Therefore, you need to first check that the id is not in use, and then set the id.  If it is in use, you need to make the id unique, perhaps adding "underscore".

Stack trace:
java.lang.IllegalArgumentException: org.sbml.jsbml.IdentifierException: Cannot set duplicate meta identifier BetI_protein for species.
	at org.sbml.jsbml.AbstractSBase.setId(AbstractSBase.java:3093)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.changeSpeciesId(BioModel.java:2245)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbmlcore.SpeciesPanel.handlePanelData(SpeciesPanel.java:929)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbmlcore.SpeciesPanel.constructor(SpeciesPanel.java:630)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbmlcore.SpeciesPanel.<init>(SpeciesPanel.java:132)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.launchSpeciesPanel(ModelEditor.java:2546)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic.bringUpEditorForCell(Schematic.java:2355)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic$9.mouseReleased(Schematic.java:1165)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.sbml.jsbml.IdentifierException: Cannot set duplicate meta identifier BetI_protein for species.
	at org.sbml.jsbml.AbstractSBase.setId(AbstractSBase.java:3091)
	... 40 more

**Comment by tramyn** [comment]
Update: This feature is currently supported for species. Creating unique id for promoters still has yet to be resolved because every time a species is created and then annotated with a DNA SBOL component, iBioSim will recognize it as a species type and not a promoter type. To do this last part, resolve #366 before adding code to make promoter id to be unique.

**Comment by tramyn** [comment]
Update: promoters can now handle annotating multiple promoters with the same SBOL component and unique IDs will be generated for this case.

**Comment by tramyn** [comment]
Update: 
Generating unique species id caused issues reported #416 so this implementation was taken out and retested. Therefore, this issue no longer needs testing.
