### ISSUE TITLE
Unable to perform VPR model generation from SBOLDesigner designs

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#385]
These two designs were created in SBOLDesigner:
design1: "BO_27661:prom;BO_27783:rbs;BO_32077:cds;BO_4257:ter"
design2="BO_27632:prom;BO_27783:rbs;BO_31554:cds;BO_4257:ter";

VPR model generation was then selected for the two designs and the following error was thrown:

<img width="965" alt="vprerror" src="https://user-images.githubusercontent.com/7537729/28507581-29d9f0f8-6ff1-11e7-9ad1-fb7ac0ecc316.png">

org.sbolstandard.core2.SBOLValidationException: sbol-10202: The identity property of an Identified object MUST be globally unique.
Reference: SBOL Version 2.1.0 Section 7.4 on page 17
: https://synbiohub.org/public/bsu/BO_27783_seq/1
	at org.sbolstandard.core2.SBOLDocument.addTopLevel(SBOLDocument.java:2421)
	at org.sbolstandard.core2.SBOLDocument.addSequence(SBOLDocument.java:1701)
	at org.sbolstandard.core2.SBOLDocument.createSequence(SBOLDocument.java:1124)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1320)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1163)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1139)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbol.SBOLInputDialog.getSelection(SBOLInputDialog.java:379)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbol.SBOLInputDialog.getInput(SBOLInputDialog.java:513)
	at edu.utah.ece.async.ibiosim.gui.Gui.openSBOLOptions(Gui.java:6322)
	at edu.utah.ece.async.ibiosim.gui.Gui.executeMouseClickEvent(Gui.java:8148)
	at edu.utah.ece.async.ibiosim.gui.Gui.mouseClicked(Gui.java:8907)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
Same bug as #388

**Comment by tramyn** [comment]
Fixed and tested.
