### ISSUE TITLE
Unable to perform VPR model generation from command line

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#386]
Attempted to run designs for VPR model generation on command line with the attached model and got the following error:

ERROR: Unable to Perform VPR Model Generation
uk.ac.ncl.ico2s.VPRException
	at uk.ac.ncl.ico2s.sbolstack.TripleStoreHandler.executeSparql(TripleStoreHandler.java:46)
	at uk.ac.ncl.ico2s.sbolstack.SBOLStackHandler.getInteractions(SBOLStackHandler.java:26)
	at uk.ac.ncl.ico2s.sbolstack.SBOLInteractionAdder_GeneCentric.addInteractions(SBOLInteractionAdder_GeneCentric.java:145)
	at uk.ac.ncl.ico2s.sbolstack.SBOLInteractionAdder_GeneCentric.getInteractions(SBOLInteractionAdder_GeneCentric.java:135)
	at uk.ac.ncl.ico2s.sbolstack.SBOLInteractionAdder_GeneCentric.addInteractions(SBOLInteractionAdder_GeneCentric.java:43)
	at edu.utah.ece.async.ibiosim.conversion.VPRModelGenerator.generateModel(VPRModelGenerator.java:57)
	at edu.utah.ece.async.ibiosim.conversion.VPRModelGenerator.main(VPRModelGenerator.java:134)
	at edu.utah.ece.async.ibiosim.conversion.ModelGeneratorTests.test_file(ModelGeneratorTests.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: HttpException: 404
	at org.apache.jena.sparql.engine.http.HttpQuery.execPost(HttpQuery.java:396)
	at org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:291)
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:345)
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:337)
	at uk.ac.ncl.ico2s.sbolstack.TripleStoreHandler.executeSparql(TripleStoreHandler.java:35)
	... 30 more

**Comment by tramyn** [comment]
This has been fixed and tested.
