### ISSUE TITLE
Attempted to import my SBOL model

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#387]
iBioSim Version 2.9.6

Operating system: Linux

Bug reported by: pdun2008@gmail.com

Description:

Stack trace:
java.lang.IllegalArgumentException: Cannot set invalid SBO term -1 because it must not be smaller than zero or larger than 9999999.
	at org.sbml.jsbml.AbstractSBase.setSBOTerm(AbstractSBase.java:2648)
	at org.sbml.jsbml.AbstractSBase.setSBOTerm(AbstractSBase.java:2669)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.createBiochemicalReaction(BioModel.java:1057)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateBiochemicalRxn(SBOL2SBML.java:508)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateModel(SBOL2SBML.java:231)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateSubModel(SBOL2SBML.java:326)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateModel(SBOL2SBML.java:265)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateSubModel(SBOL2SBML.java:326)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateModel(SBOL2SBML.java:265)
	at edu.utah.ece.async.ibiosim.gui.Gui.generateSBMLFromSBOL(Gui.java:6570)
	at edu.utah.ece.async.ibiosim.gui.Gui.importSBOLFile(Gui.java:5151)
	at edu.utah.ece.async.ibiosim.gui.Gui.importSBOL(Gui.java:5177)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2992)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tramyn** [comment]
Hi pdun,
Could you provide me your SBOL data file?

Thanks,

Tramy Nguyen

**Comment by tramyn** [comment]
Update: Peter have tried importing the following SBOL data file. 

[ATGC_SBOL.xml.zip](https://github.com/MyersResearchGroup/iBioSim/files/1171903/ATGC_SBOL.xml.zip)

I have tried importing this file on my version of iBioSim from my MacBook Pro and it works without any error.

**Comment by tramyn** [comment]
Update: Chris has resolved this issue by reporting the following.

You are using the wrong namespace for SBO.  It should be:
http://identifiers.org/biomodels.sbo/SBO:0000xxx
