### ISSUE TITLE
Exception trying to open species in schematic in analysis view

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#399]
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbmlcore.SpeciesPanel.constructor(SpeciesPanel.java:375)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbmlcore.SpeciesPanel.<init>(SpeciesPanel.java:132)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.launchSpeciesPanel(ModelEditor.java:2512)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic.bringUpEditorForCell(Schematic.java:2304)

**Comment by leandrohw** [comment]
b3dec22 
problem was in interesting species list.

**Comment by cjmyers** [comment]
Works.
