### ISSUE TITLE
this error popped up when changing the name of the promoter

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#416]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: mginleyh@gmail.com

Description:

Stack trace:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.changePromoterId(BioModel.java:2213)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.gcm.PromoterPanel.openGui(PromoterPanel.java:549)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.gcm.PromoterPanel.<init>(PromoterPanel.java:405)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.launchPromoterPanel(ModelEditor.java:2475)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic.bringUpEditorForCell(Schematic.java:2806)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic$9.mouseReleased(Schematic.java:1166)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
[r6_const.zip](https://github.com/MyersResearchGroup/iBioSim/files/1326854/r6_const.zip)

**Comment by cjmyers** [comment]
Added null pointer check which removes the exception.  However, still not sure how this file ended up in a state without a production reaction for the promoter.

**Comment by cjmyers** [comment]
@tramyn I removed the call to change the promoter id based on the id in the SBOL that is attached.  I think this causes name conflicts problems especially if you include the same SBOL record on more than one species.  It is okay to copy the name, SBO term, etc., but id is tricky.

**Comment by tramyn** [comment]
This has been tested on SBML species. I have tried:
- annotating an SBML species with an SBOL protein
- annotating an SBML element with an SBOL promoter
