### ISSUE TITLE
mix of complex and reversable reaction crash

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#420]
iBioSim Version 3.0.0-beta

Operating system: Windows 10

Bug reported by: spencer.purves31@gmail.com

Description:

Stack trace:
java.lang.NumberFormatException: For input string: "1.#INF"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at edu.utah.ece.async.ibiosim.dataModels.util.dataparser.TSDParser.<init>(TSDParser.java:158)
	at edu.utah.ece.async.ibiosim.gui.graphEditor.Graph.readData(Graph.java:645)
	at edu.utah.ece.async.ibiosim.gui.graphEditor.Graph.refresh(Graph.java:6421)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.updateTSDGraph(AnalysisView.java:3217)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:961)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:40)

**Comment by cjmyers** [comment]
Not sure how to reproduce.  Closing.
