### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by eyesmo** [MyersResearchGroup/iBioSim#433]
Hi again! I'm now 2 for 3 on the installations. I got libSBOLj and SBOLDesigner build correctly, but am getting hung up on iBioSim. I ran
>git clone https://github.com/MyersResearchGroup/iBioSim.git

entered /iBioSim, and ran
>mvn clean install -e

And got the following output:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] iBioSim ............................................ SUCCESS [  0.330 s]
[INFO] iBioSim-dataModels ................................. FAILURE [  0.449 s]
[INFO] iBioSim-conversion ................................. SKIPPED
[INFO] LEMA-verification .................................. SKIPPED
[INFO] iBioSim-analysis ................................... SKIPPED
[INFO] iBioSim-learn ...................................... SKIPPED
[INFO] iBioSim-synthesis .................................. SKIPPED
[INFO] iBioSim-gui ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.005 s
[INFO] Finished at: 2017-11-15T18:27:45-06:00
[INFO] Final Memory: 10M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project iBioSim-dataModels: Could not resolve dependencies for project edu.utah.ece.async:iBioSim-dataModels:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project iBioSim-dataModels: Could not resolve dependencies for project edu.utah.ece.async:iBioSim-dataModels:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project edu.utah.ece.async:iBioSim-dataModels:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:208)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:393)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:376)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.sbml.libsbml:libsbml:jar:1.0.0 in http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:240)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:215)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:594)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:512)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :iBioSim-dataModels

**Comment by cjmyers** [comment]
Please try:

mvn clean
mvn install

Chris

**Comment by eyesmo** [comment]
Success! Thanks ^.^

**Comment by cjmyers** [comment]
Need to update the documentation on this one actually.

**Comment by leandrohw** [comment]
Fixed.

**Comment by eyesmo** [comment]
One more question about running iBioSim (and this is probably just me not knowing how things work):

Following the README, I tried copying /gui/target/iBioSim-gui-3.0.0-SNAPSHOT-jar-with-dependencies.jar to /bin/ with
>cp gui/target/iBioSim-gui-3.0.0-SNAPSHOT-jar-with-dependencies.jar /bin

but got
>cp: /bin/iBioSim-gui-3.0.0-SNAPSHOT-jar-with-dependencies.jar: Operation not permitted

I was able to manually duplicate the file, move it to /bin/ and rename it iBioSim.jar. The README then says to run 
>iBioSim.mac64

in the /bin/ directory. I moved to /bin/ and tried
>iBioSim.mac64

But got 
>-bash: iBioSim.mac64: command not found

I feel like this is just me not fully understanding what was meant by 'run iBioSim.mac64'. What's the command I should use?

**Comment by cjmyers** [comment]
I think the problem with your copy is that you used “/bin” and what is meant is to: <path of you iBioSim install>/bin  

This could perhaps be described a bit clearly, but it is tricky since everyone may have a different target path.

As for running, I think you need:

./iBioSim.mac64

This reason you might need the first part is if the “.” (i.e., current directory) is not part of your path.

Please let us know if this works for you.

**Comment by eyesmo** [comment]
Thanks! You were right about the copy command; it works when I use the full path for the file and the end directory.

./iBioSim.mac64 works gets the GUI to attempt start up (as does listing the full path to iBioSim.mac64). However, the GUI never finishes loading, and instead I get
>UnsatisfiedLinkError: libsbml not found
>java.lang.UnsatisfiedLinkError: no sbmlj in java.library.path
>	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>	at java.lang.System.loadLibrary(System.java:1122)
>	at edu.utah.ece.async.ibiosim.gui.Gui.main(Gui.java:8927)
>dyld: Library not loaded: /usr/local/lib/libgsl.19.dylib
>  Referenced from: /usr/local/Cellar/ibiosim/bin/../bin/reb2sac.mac64
>  Reason: image not found
>ERROR: reb2sac.mac64 not functional (134).
>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

If I'm reading that correctly, am I missing the libsbml dependency?

**Comment by cjmyers** [comment]
Yes, this does sound like libsbml did not get properly installed.  Can you run this command and send me what you see?

ls /usr/local/lib/libsbml*

**Comment by eyesmo** [comment]
I get
>/usr/local/lib/libsbml-static.a		/usr/local/lib/libsbml.5.dylib
>/usr/local/lib/libsbml.5.15.0.dylib	/usr/local/lib/libsbml.dylib

**Comment by cjmyers** [comment]
It looks like you have an older library and you are also missing the java bindings.  The second is probably the bigger problem.  The version we are expecting you to install is here:

https://sourceforge.net/projects/sbml/files/libsbml/5.15.2-experimental/

**Comment by eyesmo** [comment]
Making progress! I installed the latest macOS Sierra version, and now the output when I try to run iBioSim is
>dyld: Library not loaded: /usr/local/lib/libgsl.19.dylib
>  Referenced from: /usr/local/Cellar/ibiosim/bin/../bin/reb2sac.mac64
>  Reason: image not found
>ERROR: reb2sac.mac64 not functional (134).
>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

So if I'm reading this right, the libsbml dependency has been satisfied, but I now need to get a functional version of dyld/dylib/reb2sac?

**Comment by cjmyers** [comment]
Yes, it appears that libgsl is missing or has the wrong version installed.  Can you try this and let me know what you see?

ls /usr/local/lib/libgsl*

**Comment by eyesmo** [comment]
>No such file or directory

Is libgsl the GNU Scientific Library? Should I install from here? https://www.gnu.org/software/gsl/

**Comment by cjmyers** [comment]
Yes, you should see a link on the reb2sac installation page.  Did you install reb2sac and GeneNet or just use the checked in versions of these programs?

**Comment by eyesmo** [comment]
I don't think I had either of those installed. I've now installed libgsl and reb2sac now (at least I think I have; a bunch of stuff happened and no errors were thrown when I ran 'configure && make && make install' in their folders), though I can't find installation instructions for GeneNet. Now when I run iBioSim I get 
>dyld: Library not loaded: /usr/local/lib/libgsl.19.dylib
>  Referenced from: /usr/local/Cellar/ibiosim/bin/../bin/reb2sac.mac64
>  Reason: image not found
>ERROR: reb2sac.mac64 not functional (134).
>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

I checked /usr/local/lib, and sure enough, there was no libgsl.19.dylib. However, there was a libgsl.23.dylib, libgsl.a, libgsl.dylib, and libgsl.la.

**Comment by cjmyers** [comment]
The GeneNet instructions are here, but the version that you get from github is likely fine.

https://github.com/MyersResearchGroup/GeneNet

The version of reb2sac though is not working for you as you have a more recent gsl library.  Please note that after making reb2sac, you need to copy the generated binary to <iBioSim path>/bin/reb2sac.mac64 in order to replace it with the one you built.

**Comment by eyesmo** [comment]
Cool. I've got GeneNet installed now.
What's the name of the binary file I need to copy into usr/local/Cellar/ibiosim/bin/reb2sac.mac64?
Here's what's currently in reb2sac:
>/usr/local/Cellar/reb2sac ⚽️ ls
>COPYING				config.sub
>Doxyfile			configure
>INSTALL				configure.in
>LICENSE				depcomp
>Makefile			install-reb2sac-cygwin.sh
>Makefile.am			install-reb2sac-linux.sh
>Makefile.cvs			install-reb2sac-macos.sh
>Makefile.in			install-sh
>README.md			libtool
>aclocal.m4			ltmain.sh
>build.xml			missing
>config.guess			mkinstalldirs
>config.h			reb2sac.kdevelop
>config.h.in			src
>config.log			stamp-h1
>config.status			templates

**Comment by cjmyers** [comment]
If you have run “make install”, you should find it in “/usr/local/bin/reb2sac”

We should likely just make it find it there, but for historical reasons we have it use the one in <iBioSim>/bin

**Comment by eyesmo** [comment]
WAIT A MINUTE, does /bin mean /binaries?! That makes so much more sense now!
Okay, so in /usr/local/bin I found a binary called reb2sac. I copied that to /usr/local/Cellar/ibiosim/bin/reb2sac.mac64 with
>cp /usr/local/bin/reb2sac /usr/local/Cellar/ibiosim/bin/reb2sac.mac64

replacing the old incompatible binary in the process. Now when I run iBioSim I get
> :  : 	could not read from file 
>usage: reb2sac [options] <source-filename>
>where options are:
>--<key>=<value> predefined keys are:
>source.encoding, target.encoding, out and reb2sac.properties
>--source.encoding=sbml is default
>--target.encoding=hse2 is default
>--out=<target-filename> if this option is not provided, the target filename is specified by backend
>--reb2sac.properties=default is default
>--reb2sac.properties.file can be used to specfied a properties file for default reb2sac properties >handler
>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

**Comment by cjmyers** [comment]
It is working now.  The message below is normal.

**Comment by eyesmo** [comment]
Great! Is there a quick and easy way to open an example model to play with/make sure everything is working properly?

**Comment by cjmyers** [comment]
Try the first few steps of this tutorial:

http://www.async.ece.utah.edu/tools/BioSim/docs/iBioSim_SynBio_Tutorial.html

Note it is a bit out-of-date so somethings might look slightly different, but importing and simulating a BioModel should still work about the same.

**Comment by eyesmo** [comment]
Thanks so much! It's working pretty well. One issue I'm having is finding/associating the toggle switch subcomponent sequences with the model I'm building. I can find and import GeneticToggle.sbol, after which it tells me
<img width="451" alt="screen shot 2017-11-17 at 3 55 06 pm" src="https://user-images.githubusercontent.com/2289040/32970719-b6e3998a-cbaf-11e7-849e-b51e195885b2.png">

However, when I click the model button, I can't find the Associate SBOL button:
<img width="624" alt="screen shot 2017-11-17 at 3 57 13 pm" src="https://user-images.githubusercontent.com/2289040/32970785-01287862-cbb0-11e7-8424-9b6528b6eacb.png">

When I click Add/Edit SBOL part it asks me 
<img width="890" alt="screen shot 2017-11-17 at 3 57 51 pm" src="https://user-images.githubusercontent.com/2289040/32970813-1a89f4c0-cbb0-11e7-84d2-691d928f33dd.png">

I've been able to locate and associate the LacI inverter and TetR inverter components with their respective SBOL parts, but I'm having difficulty associating the two parts together into a composite.

**Comment by cjmyers** [comment]
Great.  Could we perhaps move this discussion off the issue tracker? You can email me at myers@ece.utah.edu?

Yes, this is an area that has changed a lot since the tutorial was written.  Creating the composite is an area that has changed a lot.  I would skip over that part of the tutorial.  There is also a second tutorial that might be of interested for Systems Biology using phage lambda.  Both tutorials and our documentation in general though are sadly getting a bit behind the times *sigh*.  Never enough time to keep these up-to-date with all the changes.  Perhaps we can discuss at some point what you would like to be able to do, and I can give more direct guidance.

**Comment by eyesmo** [comment]
Okay! I'll email you.
