### ISSUE TITLE
Tried to run an Analysis of the GeneticToggle circuit I built following the tutorial, but instead java threw a nullpointerexception.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#435]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: ilarkin@u.northwestern.edu

Description:

Stack trace:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.Evaluator.evaluateExpressionRecursive(Evaluator.java:54)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.Evaluator.evaluateOperator(Evaluator.java:745)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.Evaluator.evaluateExpressionRecursive(Evaluator.java:72)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.Evaluator.evaluateOperator(Evaluator.java:734)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.Evaluator.evaluateExpressionRecursive(Evaluator.java:72)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.math.ReactionNode.computePropensity(ReactionNode.java:104)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.HierarchicalSimulation.computeFixedPoint(HierarchicalSimulation.java:897)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.methods.HierarchicalODERKSimulator.initialize(HierarchicalODERKSimulator.java:153)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.methods.HierarchicalODERKSimulator.simulate(HierarchicalODERKSimulator.java:177)
	at edu.utah.ece.async.ibiosim.analysis.simulation.DynamicSimulation.simulate(DynamicSimulation.java:135)
	at edu.utah.ece.async.ibiosim.analysis.Run.executeSimulation(Run.java:550)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:139)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:923)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:40)

**Comment by leandrohw** [comment]
Could you send us the file you are testing this with? For now, you can use
the rk45 simulation method.
