### ISSUE TITLE
With libsbml 5.16.0 installed, iBioSim cannot find it.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#465]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: zhen.zhang@usu.edu

Description:
This happens when clicking on an XML file in the GUI.

Stack trace:
java.lang.NoClassDefFoundError: Could not initialize class org.sbml.libsbml.libsbmlJNI
	at org.sbml.libsbml.SBMLReader.<init>(SBMLReader.java:105)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.readSBML(SBMLutilities.java:5746)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.loadSBMLFile(BioModel.java:5487)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.load(BioModel.java:2154)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.<init>(ModelEditor.java:270)
	at edu.utah.ece.async.ibiosim.gui.Gui.openSBML(Gui.java:5791)
	at edu.utah.ece.async.ibiosim.gui.Gui.executeMouseClickEvent(Gui.java:7109)
	at edu.utah.ece.async.ibiosim.gui.Gui.mouseClicked(Gui.java:7866)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zgzn** [comment]
This was due to the following missing VM arguments: 
-Dapple.laf.useScreenMenuBar=true -Xdock:name="iBioSim" -Xdock:icon=Users/myers/git/iBioSim/gui/src/main/resources/edu/utah/ece/async/ibiosim/gui/icons/iBioSim.png -Djava.library.path=/usr/local/lib

With them, the errors disappeared.

**Comment by cjmyers** [comment]
I'm reopening as an exception is not the right behavior.

**Comment by cjmyers** [comment]
This no longer throw an exception when libsbml is not found.
