### ISSUE TITLE
Exception in hierarchical simulator

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#466]
java.io.IOException: Stream closed
	at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
	at java.io.BufferedWriter.write(BufferedWriter.java:221)
	at java.io.Writer.write(Writer.java:157)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.io.HierarchicalTSDWriter.close(HierarchicalTSDWriter.java:81)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.HierarchicalSimulation.closeWriter(HierarchicalSimulation.java:711)
	at edu.utah.ece.async.ibiosim.analysis.simulation.hierarchical.methods.HierarchicalODERKSimulator.simulate(HierarchicalODERKSimulator.java:219)
	at edu.utah.ece.async.ibiosim.analysis.simulation.DynamicSimulation.simulate(DynamicSimulation.java:135)
	at edu.utah.ece.async.ibiosim.analysis.Run.executeSimulation(Run.java:566)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:164)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:926)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:40)

**Comment by leandrohw** [comment]
Fixed in #469
