### ISSUE TITLE
URI Prefix Exception

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#481]
When opening up an old iBioSim project (attached to this issue), I came across this error:

Because this is an "Unhandled Exception", we should figure out how to report this error appropriately. 

<img width="741" alt="screen shot 2018-01-18 at 4 27 29 pm" src="https://user-images.githubusercontent.com/7537729/35122419-b1a609ba-fc6c-11e7-929d-3505e89092af.png">

java.lang.IllegalArgumentException: Unable to set default URI prefix to non-compliant value ` http://dummy.org/'
	at org.sbolstandard.core2.SBOLDocument.setDefaultURIprefix(SBOLDocument.java:4006)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:568)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:457)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:383)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:368)
	at edu.utah.ece.async.ibiosim.dataModels.sbol.SBOLUtility.loadSBOLFile(SBOLUtility.java:101)
	at edu.utah.ece.async.ibiosim.gui.Gui.readSBOLDocument(Gui.java:4038)
	at edu.utah.ece.async.ibiosim.gui.Gui.openProject(Gui.java:1300)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2370)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
 
[issue406.zip](https://github.com/MyersResearchGroup/iBioSim/files/1644509/issue406.zip)

**Comment by tramyn** [comment]
Update: Loophole to avoid this error is to make sure Owner's domain, found in iBioSim's preferences, must be set to a different URI that is not "http://dummy.org/"

**Comment by cjmyers** [comment]
I think it might be due to the trailing slash.  I think it should be http://dummy.org <http://dummy.org/>

**Comment by cjmyers** [comment]
Actually, it is not the trailing slash.  It seems there might have been some other issue with your URI prefix.  I think preference editor needs to validate the URI prefix so it can give a good error message.

**Comment by cjmyers** [comment]
Now gives an error message when an invalid domain is provided in the preference and will not save this.
