### ISSUE TITLE
four productions appeared when I cancelled an edit

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#507]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: jakebeal@gmail.com

Description:

Stack trace:
Property fast is not defined in reaction for Level 3 and Version 2.
	at org.sbml.jsbml.Reaction.getFast(Reaction.java:596)
	at org.sbml.jsbml.Reaction.equals(Reaction.java:457)
	at java.util.ArrayList.remove(ArrayList.java:532)
	at org.sbml.jsbml.ListOf.remove(ListOf.java:856)
	at org.sbml.jsbml.AbstractTreeNode.removeFromParent(AbstractTreeNode.java:700)
	at org.sbml.jsbml.Model.remove(Model.java:4940)
	at org.sbml.jsbml.Model.removeReaction(Model.java:5152)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.removeReaction(BioModel.java:2669)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic.removeCells(Schematic.java:1587)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.Schematic.cut(Schematic.java:425)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.cut(ModelEditor.java:2822)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:3066)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:811)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
I think this one is fixed in latest.
