### ISSUE TITLE
When the .sbol file was clicked.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#509]
iBioSim Version 3.0.0-beta

Operating system: Windows 10

Bug reported by: pfontanarrosa@gmail.com

Description:
I have this project without any sbol sequences uploaded, section was clicked, this error message popped up.

Stack trace:
java.lang.IllegalAccessError: tried to access field edu.utah.ece.async.sboldesigner.sbol.editor.dialog.InputDialog.cancelButton from class edu.utah.ece.async.ibiosim.gui.modelEditor.sbol.SBOLInputDialog
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbol.SBOLInputDialog.initGUI(SBOLInputDialog.java:554)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.sbol.SBOLInputDialog.getInput(SBOLInputDialog.java:523)
	at edu.utah.ece.async.ibiosim.gui.Gui.openSBOLOptions(Gui.java:5871)
	at edu.utah.ece.async.ibiosim.gui.Gui.executeMouseClickEvent(Gui.java:7174)
	at edu.utah.ece.async.ibiosim.gui.Gui.mouseClicked(Gui.java:7939)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by cjmyers** [comment]
The problem was that it was run using 32-bit Java, but it requires 64-bit java to allocate this much memory.
