### ISSUE TITLE
State-based abstraction seems broken

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#512]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: zhen.zhang@usu.edu

Description:
It looks like any state-based analysis in the analysis view generates this exception. Tried on an existing analysis view (dual_feedback_oscillator).

Stack trace:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.analysis.Run.executeMarkov(Run.java:295)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:157)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:903)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)

**Comment by zgzn** [comment]
The dual_feedback_oscillator analysis view caused this exception.
[stochastic_model_checking.zip](https://github.com/MyersResearchGroup/iBioSim/files/1858859/stochastic_model_checking.zip)

**Comment by cjmyers** [comment]
This should be fixed now.  Please test @zgzn

**Comment by zgzn** [comment]
This seems to be fixed now. Closing.
