### ISSUE TITLE
Calling PRISM probably needs to get its path

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#514]
It seems that iBioSim assumes the analysis view directory is the directory for PRISM. I got the error message below when using this option. PRISM is installed on a different directory on my machine, and I was able to run verification with PRISM in a terminal.

java.io.IOException: Cannot run program "prism" (in directory "/Users/zhangz/research/lpn/genetic_circuits/stochastic_model_checking/dual_feedback_oscillator"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at edu.utah.ece.async.ibiosim.analysis.Run.executePrism(Run.java:657)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:152)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:903)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more

**Comment by zgzn** [comment]
I think I know the reason. I invoked iBioSim within Eclipse. In the run environment for iBioSim, my PATH was set to "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/zhangz/myBioSim/iBioSim/bin". The path for PRISM is declared in my .profile file, but not in the PATH environment. Even though on the bottom of the attached screenshot I had "Append environment to native environment". I assumed this meant all paths declared in .profile were inherited. But it seems that the PATH declared in the run environment   replaces that declared in .profile.
