### ISSUE TITLE
Conversion of SBML constraint to PRSIM CSL transient property seems broken

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#519]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: zhen.zhang@usu.edu

Description:
Conversion of SBML constraint describing transient probabilistic property generated this bug. See constraint2 on the analysis view "toggle_switch" for toggle_switch.xml in the attachment in the next comment. We disabled all other constraints. The generated PCTL property file was empty. However, running this example with steady-state properties (constraints 0 and 1) did not encounter this issue, and valid PRISM CSL properties were generated.

Stack trace:
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.sbml.jsbml.ASTNode.getChild(ASTNode.java:2498)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.convertMath2PrismProperty(SBMLutilities.java:1667)
	at edu.utah.ece.async.lema.verification.lpn.LPN.convertLPN2PRISM(LPN.java:491)
	at edu.utah.ece.async.ibiosim.analysis.Run.executePrism(Run.java:651)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:152)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:903)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)

**Comment by zgzn** [comment]
See constraint2 on the analysis view "toggle_switch" for toggle_switch.xml. 
[Uploading stochastic_model_checking.zip…]()

**Comment by zgzn** [comment]
Fixed.
