### ISSUE TITLE
java.lang.NullPointerException 	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:863) 	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#601]
iBioSim Version 3.0.0

Operating system: Mac OS X

Bug reported by: criera-ruiz@huskers.unl.edu

Description:

Stack trace:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:863)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)

**Comment by cjmyers** [comment]
Could you share some more details about how this bug occurred.  Namely, what type of analysis were you doing?  Also, if you can share the project you were doing analysis on, it would help.
