### ISSUE TITLE
Cannot Upload project to SynBioHub.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#605]
iBioSim Version 3.0.0

Operating system: Windows 10

Bug reported by: pfontanarrosa@gmail.com

Description:
When trying to upload, I get the following error:
org.synbiohub.frontend.SynBioHubException: 400 org.sbolstandard.core2.SBOLValidationException: sbol-10809:
If a MapsTo is contained by a Module
 then the remote property of the MapsTo MUST refer to a FunctionalComponent in the ModuleDefinition that is referenced by the definition property of the Module.
Reference: SBOL Version 2.3.0 Section 7.7.3 on page 29
:https://synbiohub.org/user/pfontanarrosa/Testingupload/Simulation_Environment_md/C1/YFP/1
	at org.sbolstandard.core2.MapsTo.setRemote(MapsTo.java:242)
	at org.sbolstandard.core2.SBOLDocument.updateReferences(SBOLDocument.java:3122)
	at org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(SBOLDocument.java:3310)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:349)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Fontanapink** [comment]
Here is the project I am trying to upload.
[UploadProject.zip](https://github.com/MyersResearchGroup/iBioSim/files/4723816/UploadProject.zip)

**Comment by cjmyers** [comment]
I imported this OMEX file into a new project and uploaded successfully.  Is this still having problems for you?  Sorry for the long long delay on this one.
