### ISSUE TITLE
Java Array index Error in SSA-Direct Reaction-based Abstraction

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#609]
iBioSim Version 3.0.0

Operating system: Windows 10

Bug reported by: micotner9@gmail.com

Description:
When trying to preform a reaction-based abstraction on my model using the SSA-Direct (Dynamic) simulator, iBioSim immediately throws an error: "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0"
The model is BIOMD0000000565 from the EMBL-EBI BioModels database. All simulation options were left as default except: Abstraction was set to Reaction-based, analysis type was set to Monte Carlo, and Possible Simulators/Analyzers was set to SSA-Direct (Dynamic).

Stack trace:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.sbml.jsbml.ASTNode.getChild(ASTNode.java:2498)
	at org.sbml.jsbml.ASTNode.getLeftChild(ASTNode.java:2620)
	at edu.utah.ece.async.ibiosim.analysis.simulation.flattened.Simulator.setupSingleReaction(Simulator.java:6299)
	at edu.utah.ece.async.ibiosim.analysis.simulation.flattened.Simulator.setupReactions(Simulator.java:6548)
	at edu.utah.ece.async.ibiosim.analysis.simulation.flattened.SimulatorSSADirect.initialize(SimulatorSSADirect.java:270)
	at edu.utah.ece.async.ibiosim.analysis.simulation.flattened.SimulatorSSADirect.<init>(SimulatorSSADirect.java:51)
	at edu.utah.ece.async.ibiosim.analysis.simulation.DynamicSimulation.simulate(DynamicSimulation.java:98)
	at edu.utah.ece.async.ibiosim.analysis.Run.executeSimulation(Run.java:466)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:148)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:907)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)

**Comment by michaelcotner** [comment]
The model that I used was downloaded from https://www.ebi.ac.uk/biomodels-main/BIOMD0000000565

**Comment by zgzn** [comment]
@cjmyers This is the error for the multi-compartment SBML model we emailed you before. Can you give us pointers on how to fix it? Thanks.

**Comment by cjmyers** [comment]
Please try this again using the rkf45 ODE simulation method (the method you used is not very stable).  If you don't see this one, please make sure you have reb2sac installed.  This is also a stiff model, so I set a time limit of 1.0 seconds.  It take a long time to simulate, so it likely has a very fast time constants.  Do not use abstraction on this model as it will not help.
