### ISSUE TITLE
Problem with importing BioModel

### ISSUE THREAD

**Issue by LukasBuecherl** [MyersResearchGroup/iBioSim#612]
When using the download function to download a BioModel (in this case #507 Toggle Switch), I get the following error:

java.lang.UnsatisfiedLinkError: 'java.lang.String org.sbml.libsbml.libsbmlJNI.L3v2extendedmathExtension_getXmlnsL3V1V1()'
	at org.sbml.libsbml.libsbmlJNI.L3v2extendedmathExtension_getXmlnsL3V1V1(Native Method)
	at org.sbml.libsbml.L3v2extendedmathExtension.getXmlnsL3V1V1(L3v2extendedmathExtension.java:70)
	at org.sbml.libsbml.libsbml.DowncastSBMLNamespaces(libsbml.java:249)
	at org.sbml.libsbml.SBase.getSBMLNamespaces(SBase.java:558)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.convertToL3(SBMLutilities.java:5707)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.readSBML(SBMLutilities.java:5815)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.loadSBMLFile(BioModel.java:6141)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.load(BioModel.java:2808)
	at edu.utah.ece.async.ibiosim.gui.Gui.canDelete(Gui.java:9136)
	at edu.utah.ece.async.ibiosim.gui.Gui.overwrite(Gui.java:8949)
	at edu.utah.ece.async.ibiosim.gui.Gui.downloadBioModel(Gui.java:2917)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2412)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:690)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:649)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by cjmyers** [comment]
@LukasBuecherl Can we close this one now?

**Comment by LukasBuecherl** [comment]
The problem was fixed by installing the correct version of libSBML 5.18.0
