### ISSUE TITLE
Level mismatch between listOfUnitDefinitions in Level2 and unitDefinition in Level 3

### ISSUE THREAD

**Issue by LukasBuecherl** [MyersResearchGroup/iBioSim#622]
Tried to apply reaction-based abstraction to a model. When I ran the analysis view with the abstraction and model settings I got that error.

Level mismatch between listOfUnitDefinitions in Level 2 and unitDefinition in Level 3
	at org.sbml.jsbml.AbstractSBase.checkLevelAndVersionCompatibility(AbstractSBase.java:873)
	at org.sbml.jsbml.AbstractSBase.registerChild(AbstractSBase.java:2174)
	at org.sbml.jsbml.ListOf.add(ListOf.java:444)
	at org.sbml.jsbml.Model.addUnitDefinition(Model.java:606)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.network.GeneticNetwork.getUnitString(GeneticNetwork.java:1077)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.network.GeneticNetwork.getMoleTimeParameter(GeneticNetwork.java:1105)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.visitor.PrintDecaySpeciesVisitor.addDecayUnit(PrintDecaySpeciesVisitor.java:59)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.visitor.PrintDecaySpeciesVisitor.<init>(PrintDecaySpeciesVisitor.java:55)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.network.GeneticNetwork.printDecay(GeneticNetwork.java:643)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.network.GeneticNetwork.outputSBML(GeneticNetwork.java:240)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.network.GeneticNetwork.mergeSBML(GeneticNetwork.java:307)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.createSBML(ModelEditor.java:1812)
	at edu.utah.ece.async.ibiosim.gui.modelEditor.schematic.ModelEditor.saveParams(ModelEditor.java:1239)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.executeRun(AnalysisView.java:1540)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2268)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by LukasBuecherl** [comment]
Problem was due to an old SBML file in the project. Will close the issue.
