### ISSUE TITLE
Null Pointer Exception when importing 

### ISSUE THREAD

**Issue by LukasBuecherl** [MyersResearchGroup/iBioSim#624]
When I try to import the attached SBOL file I get the following error:

java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.getArraysSBasePlugin(SBMLutilities.java:5002)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.dimensionsMatch(SBMLutilities.java:5014)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.copyDimensionsToEdgeIndex(SBMLutilities.java:464)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.parser.BioModel.addRepressorToProductionReaction(BioModel.java:1568)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateRepressorReference(SBOL2SBML.java:984)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateProductionRxn(SBOL2SBML.java:929)
	at edu.utah.ece.async.ibiosim.conversion.SBOL2SBML.generateModel(SBOL2SBML.java:420)
	at edu.utah.ece.async.ibiosim.gui.Gui.generateSBMLFromSBOL(Gui.java:6222)
	at edu.utah.ece.async.ibiosim.gui.Gui.importSBOLFile(Gui.java:4760)
	at edu.utah.ece.async.ibiosim.gui.Gui.importSBOL(Gui.java:4826)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2400)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:690)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:649)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchT
[Sensor_Entrega1.xml.zip](https://github.com/MyersResearchGroup/iBioSim/files/9600798/Sensor_Entrega1.xml.zip)
hread.java:90)

**Comment by cjmyers** [comment]
I've added a few null pointer checks to eliminate the exception.  However, the file is problematic for conversion, so it will not produce a meaningful model.
