### ISSUE TITLE
Bug importing file and when starting iBioSim

### ISSUE THREAD

**Issue by PhysicsTeacher13** [MyersResearchGroup/iBioSim#634]
WARNING: Some external components are missing or have problems.
You may continue but with some loss of functionality.
GeneNet not functional (3).
 WARN (XMLNodeReader.java:261) - The type of String '' on the element constraint (Constraint) is unknown! Some data might be lost.
javax.xml.stream.XMLStreamException: JSBML could not properly read file G:\Backup_2024_2025\Genetics\Eco1C1G1T1_collection.xml. Please check if it contains valid SBML. If you think it is valid, please submit a bug report to the bug tracker of JSBML.
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:325)
        at org.sbml.jsbml.SBMLReader.readSBML(SBMLReader.java:116)
        at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:105)
        at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:92)
        at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.readSBML(SBMLutilities.java:5766)
        at edu.utah.ece.async.ibiosim.gui.Gui.importCombineArchive(Gui.java:4247)
        at edu.utah.ece.async.ibiosim.gui.Gui.importArchive(Gui.java:4412)
        at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2370)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/java.awt.Component.processEvent(Component.java:6386)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ERROR (SBMLDocument.java:561) - There was an error accessing the sbml online validator!
ERROR (SBMLDocument.java:561) - There was an error accessing the sbml online validator!
 WARN (XMLNodeReader.java:261) - The type of String '' on the element constraint (Constraint) is unknown! Some data might be lost.
javax.xml.stream.XMLStreamException: JSBML could not properly read file G:\Backup_2024_2025\Genetics\Eco1C1G1T1_collection.xml. Please check if it contains valid SBML. If you think it is valid, please submit a bug report to the bug tracker of JSBML.
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:325)
        at org.sbml.jsbml.SBMLReader.readSBML(SBMLReader.java:116)
        at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:105)
        at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:92)
        at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.readSBML(SBMLutilities.java:5766)
        at edu.utah.ece.async.ibiosim.gui.Gui.importSBMLFile(Gui.java:3712)
        at edu.utah.ece.async.ibiosim.gui.Gui.importCombineArchive(Gui.java:4266)
        at edu.utah.ece.async.ibiosim.gui.Gui.importArchive(Gui.java:4412)
        at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2370)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/java.awt.Component.processEvent(Component.java:6386)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ERROR (SBMLDocument.java:561) - There was an error accessing the sbml online validator!
ERROR (SBMLDocument.java:561) - There was an error accessing the sbml online validator!

**Comment by PhysicsTeacher13** [comment]
Importing week2 assignment.  I noticed one time I downloaded the file it
was two different sizes one was 107KB and then the same file was 10 KB
maybe there was an issue with the file on Coursera Also I can’t connect to
the sysbiohub so I had to download each part separately.  Is there network
permissions I need besides my account login?

**Comment by PhysicsTeacher13** [comment]
I am getting a message when trying to use synbiohub for parts.
Javax.net.ssl. SSL Handshake Exception: PKIX path build failed:
sun.security.provider.certpath. SunCertPathBuilderException: unable to find
valid certification path to requested target

**Comment by cjmyers** [comment]
Sorry for your issues with SynBioHub.  It is possible that SynBioHub was either down or in the process of a restart when you had these issues.  Please try logging out of SynBioHub, logging in again, and trying to download parts again.

**Comment by PhysicsTeacher13** [comment]
No luck.

I ended up downloading the collection and then adding it to iBioSim as a
local collection

**Comment by cjmyers** [comment]
Glad you found a workaround.  Sorry for the trouble.
